# Generates the image using this file
# docker build -t nocommentlab/nclvault . 

# Generates a pfx certificate on the build machine
# dotnet dev-certs https -ep /usr/share/nclvault/[certificate name] -p [password]

# docker run -p 80:80 -p 443:443 \
# -e Kestrel__Certificates__Default__Path=/app/Infrastructure/Certificate/[certificate name] \
# -e Kestrel__Certificates__Default__Password=[password] \
# -e "ASPNETCORE_URLS=https://+;http://+" \
# -v /usr/share/nclvault:/app/Infrastructure/Certificate \
# -v /usr/share/nclvault/appsettings.json:/app/appsettings.json \
# -v /usr/share/nclvault/:/app/vault \
# nocommentlab/nclvault

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

EXPOSE 80
EXPOSE 443

COPY ./linux-x64 /app
WORKDIR /app
ENTRYPOINT ["dotnet", "NclVaultAPIServer.dll"]

