name: .NET

on:
  push:
    branches: [ test-actions ]
  pull_request:
    branches: [ test-actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore .\NclVault\
    - name: Build
      run: dotnet build --no-restore .\NclVault\NclVaultAPIServer\
